### ISSUE TITLE
Issue in getting started

### ISSUE THREAD

**Issue by Nirmal1212** [hasgeek/funnel#144]
I am trying to setup the TalkFunnel. I am facing one issue while setting up on Mac OSX. 

I installed the dependencies using the below command.
```$ pip install -r requirements.txt ```

Then, renamed the settings-sample.py as settings.py after adding Access Key and Client Secret got from https://auth.hasgeek.com/apps in LASTUSER_CLIENT_ID, LASTUSER_CLIENT_SECRET

When I ran the command , ```$ python manage.py db create ``` I am getting the following error

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 300, in handle
    command.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 324, in handle
    return command.handle(app, *positional_args, **command_namespace.__dict__)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 143, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/coaster/manage.py", line 70, in create
    manager.init_for(env)
  File "/Users/nirmal/Development/web/funnel/funnel/__init__.py", line 48, in init_for
    ('codemirror-markdown', 'pygments'), 'toastr', 'baseframe-bs3', 'fontawesome>=4.0.0'
  File "/usr/local/lib/python2.7/site-packages/baseframe/__init__.py", line 118, in init_app
    networkbar_cache.init_app(app, config=nwcacheconfig)
  File "/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 161, in init_app
    self._set_cache(app, config)
  File "/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 172, in _set_cache
    import_me))
ImportError: redis is not a valid FlaskCache backend
```
When I run this ``` $ python runserver.py ```  I am getting a similar error. Is there something missing on the dependencies ?
```
Traceback (most recent call last):
  File "runserver.py", line 5, in <module>
    init_for('dev')
  File "/Users/nirmal/Development/web/funnel/funnel/__init__.py", line 48, in init_for
    ('codemirror-markdown', 'pygments'), 'toastr', 'baseframe-bs3', 'fontawesome>=4.0.0'
  File "/usr/local/lib/python2.7/site-packages/baseframe/__init__.py", line 118, in init_app
    networkbar_cache.init_app(app, config=nwcacheconfig)
  File "/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 161, in init_app
    self._set_cache(app, config)
  File "/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 172, in _set_cache
    import_me))
ImportError: redis is not a valid FlaskCache backend
```
Pls help me in setting up the environment. Thanks!

**Comment by Nirmal1212** [comment]
Hey Sorry guys. I think redis was not installed. Thats why I had the issue. But why weren't part of the requirements.txt ?

``` pip install redis ``` Used this command and now its working.

Admin please update the requirements.txt and close this issue.

**Comment by jace** [comment]
[Added upstream in Baseframe](https://github.com/hasgeek/baseframe/commit/fa20ff79dedcfebcbed32c314668faf03b6f021f) as it affects all apps. Thanks for reporting this!
