### ISSUE TITLE
Table 'proposal_label' is already defined for this MetaData instance

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#196]
When I try to run tests, i'm getting this error - 

```
Traceback (most recent call last):
  File "/home/bibhas/venvs/hasgeek/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/bibhas/venvs/hasgeek/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/bibhas/venvs/hasgeek/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/bibhas/Mordor/hasgeek/funnel/funnel/models/label.py", line 61, in <module>
    class ProposalLabel(TimestampMixin, db.Model):
  File "/home/bibhas/venvs/hasgeek/local/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 609, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 418, in __new__
    "existing Table object." % key)
InvalidRequestError: Table 'proposal_label' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

Probably because `proposal_space` is defined in 2 places? 

 1. https://github.com/hasgeek/funnel/blob/master/funnel/models/label.py#L28
 2. https://github.com/hasgeek/funnel/blob/master/funnel/models/label.py#L60

**Comment by jace** [comment]
Proposal labels are an unimplemented feature. The class at line 60 can be removed.

**Comment by jace** [comment]
@iambibhas Is this still relevant? Close if not.
